apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "redis.name" . }}
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379